minWorkers: 1
maxWorkers: 1
maxBatchDelay: 100
responseTimeout: 10800
batchSize: 1

handler:
    model_checkpoint_dir: "Meta-Llama-3-8B-Instruct-split"
    model_compiled_weights: "neuronx_artifacts"
    amp: "f16"
    tp_degree: 8
    max_length: 1024

micro_batching:
    micro_batch_size: 1 
    parallelism:
        preprocess: 2
        inference: 1
        postprocess: 2